### ISSUE TITLE
1. Dr Gelart Education offering - physician training 

### ISSUE THREAD

**Issue by dlabott** [svaughn3/v202-Maintenance-Issues#15]
@svaughn3

**Comment by svaughn3** [comment]
@dlabott 
1. Steve to follow up with Jay to write descriptions. 
2. Steve to submit descriptions to Denise for reg approval in MWS. 
3. Denise to request/'activate hcats using PDT workflow. 
4. Steve identify offerings for inclusion of hcats. 
5. Denise to export offerings and start pega. (probably multiple pegas because of multiple makes). 
6. Steve to approve pegas. 
7. Denise add to offerings. 
Goal Dec 1

**Comment by svaughn3** [comment]
@dlabott 
H80x7yy
yy = Steve to define. 
ET Employee training.  (for example).

**Comment by dlabott** [comment]
@svaughn3 
Catalog range H8000A - H8100ZZ by segment, by year, by abbreviation H80SYAA 

	S = Segment of 1 character --> CVUS | 1
	AA = 2 character abbreviation of item (i.e. RP = Report Printer)

**Comment by svaughn3** [comment]
@dlabott 
I checked with Jay and he is writing the descriptions. 
Goal to have them week following Thanksgiving.

**Comment by svaughn3** [comment]
@dlabott 
March 22, 2018 Jay emailed today, he has description written. 
approved? checking.

**Comment by svaughn3** [comment]
@dlabott 
March 27

Submitting description to Lisa for approval. 

Denise - did we assign an hcat to this?

**Comment by dlabott** [comment]
@svaughn3 
ACTION: Steve Not submitted for approval yet - still editing with Jay

**Comment by svaughn3** [comment]
@dlabott 
April 25, 2018
Description is now approved. 
DOC2124833

Can we now proceed with step 3 above ... creating the HCAT. 
The offering to include this item is the Vivid E95 CPQ_7143
Add this item to: Education and Training >> Education Courses

**Comment by svaughn3** [comment]
@dlabott 
April 26, 2018
H8018DE - checked not used in MWS. 
material class code: ?? training and supply: 0935
Action Steve: Price?

**Comment by svaughn3** [comment]
@dlabott 
July 14, 2018

New description in for approval, contains the one night hotel stay. 

Price: $6700 list, discountable, goal: $3000 net.

**Comment by svaughn3** [comment]
@dlabott 
Aug 1, 2018. 

Description waiting for Jan Tore signature. He is on vacation. No sub for him - returns Aug 6. 

Denise - I would like to get this one poised and ready to add to offering. 
I think you have to create the hcat (or maybe you already have?)

We are awaiting final approval from SDMS because we are offering education credits through their organization. approval could come any day. 
Please let me know if you need additional detail: 

1. hcat is H8018DE
2. Description in for final approval (see above)
3. price: $6700
4. discount: PSS: 52%; ZSM: 55%
5. add to offering: Vivid E95 v202 (only).

**Comment by svaughn3** [comment]
@dlabott 
Aug 6, 2018

Description is approved. 
DOC2124833

**Comment by svaughn3** [comment]
@dlabott 
Aug 6, 2018

1. 	MWS down to Aug 15, Start on H8018DE on Aug 16.
2. 	h8018DE is not listed in MWS (today)
3.  Generated PDT workflow spreadsheet, sent to Denise (H8018DE)
4.	Denise can start PCM verification and PC Assessment. 
5.  wait for MWS to come back on line : Aug 15. 
6. Verify approval from SDMS (Jenni Hintze) prior to placing this hcat into SWB.

**Comment by svaughn3** [comment]
@dlabott 
Aug 16, 2018

#6 above... SDMS approval has been received. 
REady to start MyWorkshop creation process. and then move into SWB offering. 
5.add to offering: Vivid E95 v202 (only).

**Comment by svaughn3** [comment]
@dlabott 
aug 23, 2018
problem with duplicate gems item master. being resolved 
Denise will meet with Kyle to inform of process. (proceed in parallel)

**Comment by dlabott** [comment]
@svaughn3 
Sep 6 2018
Steve to watch for MR2256672-01 route in MWS to approve.
Then Kyle Finckler QA approval
Then Denise RCL approval
Should be released after all approvals completed.

STEVE to approve workflow Step 6 and confirm list price at Step 12 and PDT process/ACTIVATE at Step 13.

DENISE to process Pega to add to offering: Vivid E95 v202 (only)

**Comment by svaughn3** [comment]
@dlabott 
Sept 13, 2018

Done - should be in SWB (VE95 offering) on Friday, sept 14 or Monday sept 17.
